// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5s9fcSOnNT681gv5bt2fiWO6D-OFqlhI',
    appId: '1:458450223719:web:13c343508d1aa29f108ac2',
    messagingSenderId: '458450223719',
    projectId: 'easyhome-6ef93',
    authDomain: 'easyhome-6ef93.firebaseapp.com',
    storageBucket: 'easyhome-6ef93.firebasestorage.app',
    measurementId: 'G-9PVY38E608',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbKvJsJ9hBOYKWS01cG-_cxTkZeeT_dBc',
    appId: '1:458450223719:android:864f7114d1d70434108ac2',
    messagingSenderId: '458450223719',
    projectId: 'easyhome-6ef93',
    storageBucket: 'easyhome-6ef93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFVbVvhjiUMDV8G0e7M1uUIeVG-KxnbPY',
    appId: '1:458450223719:ios:95f448d73f41d692108ac2',
    messagingSenderId: '458450223719',
    projectId: 'easyhome-6ef93',
    storageBucket: 'easyhome-6ef93.firebasestorage.app',
    iosBundleId: 'com.example.easyhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVbVvhjiUMDV8G0e7M1uUIeVG-KxnbPY',
    appId: '1:458450223719:ios:95f448d73f41d692108ac2',
    messagingSenderId: '458450223719',
    projectId: 'easyhome-6ef93',
    storageBucket: 'easyhome-6ef93.firebasestorage.app',
    iosBundleId: 'com.example.easyhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5s9fcSOnNT681gv5bt2fiWO6D-OFqlhI',
    appId: '1:458450223719:web:29b321de2dae417e108ac2',
    messagingSenderId: '458450223719',
    projectId: 'easyhome-6ef93',
    authDomain: 'easyhome-6ef93.firebaseapp.com',
    storageBucket: 'easyhome-6ef93.firebasestorage.app',
    measurementId: 'G-P4T8F1VQLL',
  );
}
